「PyTorchとは？」
===============================================================
【原題】：What is PyTorch?

【原著】[Soumith Chintala](http://soumith.ch/)

【元URL】https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

【翻訳】電通国際情報サービスISID AIトランスフォーメーションセンター　徳原 光

【日付】2020年10月13日

【チュトーリアル概要】

本チュートリアルでは、PyTorchでの演算処理に用いるTorch Tensorについて、その操作方法を解説します。

---



PyTorchとは？
================

PyTorchはPythonをベースとした科学計算ライブラリです。

PyTorchは以下に示す2つの機能を使いたいユーザーを対象としています。

- Numpyベースの演算の代わりに、GPUを用いた高速な演算の実施
- 高い柔軟性と実行速度を有したディープラーニングのプラットフォーム


はじめに
---------------

Tensors（テンソル）
-------------

TensorはNumPy ndarraysのような多次元配列です。

PyTorchにおいてテンソルはGPU上でも使用できるため、処理速度の向上させることも可能です。

In [ ]:
# 日本語版注：追記
%matplotlib inline


In [ ]:
from __future__ import print_function
import torch

【注意】

初期化されていない行列が宣言/作成されても、実際に使用されるまで明確な値は保有していません。宣言時にメモリ上の割り当てられた適当な値が初期値として入っています。




初期化されていない、3x5行列を生成してみましょう：



In [ ]:
x = torch.empty(5, 3)
print(x)

tensor([[2.3990e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 9.1073e-36]])


次に、乱数によって初期化された3x5行列を生成してみましょう:



In [ ]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4454, 0.5699, 0.9875],
        [0.3195, 0.7812, 0.0964],
        [0.9959, 0.0057, 0.0900],
        [0.5407, 0.4174, 0.7417],
        [0.0111, 0.2639, 0.2153]])


long型の数値0で初期化された行列を生成する場合は次の通りです:



In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接、数値を指定して行列を生成することもできます:



In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


その他に、すでにあるtensorをもとに新しくtensorを生成することもできます。

本メソッドで生成したテンソルは、テンソルの特性（例えばデータ型：dtypeなど）を、もとのtensorから引き継ぎます（ユーザーが値や特性を直接上書きしない限り）

In [ ]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-2.9226,  0.7701,  0.6173],
        [ 0.5411,  1.3643,  1.7373],
        [-0.5627,  0.8513,  0.6432],
        [ 0.8774,  0.9941,  0.2003],
        [ 0.7513, -0.7676,  0.8164]])


サイズ（size）≒テンソルの形を求めてみます:



In [ ]:
print(x.size())

torch.Size([5, 3])


【メモ】

``torch.Size``はタプルとなっているため、Pythonの通常のタプルと同様の操作が可能です。

**テンソルの操作（変形・変換等）**


PyTorchにはテンソルに対する操作（変形・変換等）が多く用意されています。

ここで、tensorを操作（変形・変換等）する追加の例を紹介します。



補足: 用例1

In [ ]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-2.7920,  1.0487,  0.9107],
        [ 1.3139,  2.2778,  1.9272],
        [-0.4863,  1.8372,  0.8573],
        [ 1.4223,  1.2303,  1.0529],
        [ 0.9580, -0.4162,  1.3788]])


補足: 用例2



In [ ]:
print(torch.add(x, y))

tensor([[-2.7920,  1.0487,  0.9107],
        [ 1.3139,  2.2778,  1.9272],
        [-0.4863,  1.8372,  0.8573],
        [ 1.4223,  1.2303,  1.0529],
        [ 0.9580, -0.4162,  1.3788]])


補足: 出力先を引数で指定 



In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-2.7920,  1.0487,  0.9107],
        [ 1.3139,  2.2778,  1.9272],
        [-0.4863,  1.8372,  0.8573],
        [ 1.4223,  1.2303,  1.0529],
        [ 0.9580, -0.4162,  1.3788]])


補足:テンソルそのものの変更（in-place）



In [ ]:
# adds x to y
y.add_(x)
print(y)

tensor([[-2.7920,  1.0487,  0.9107],
        [ 1.3139,  2.2778,  1.9272],
        [-0.4863,  1.8372,  0.8573],
        [ 1.4223,  1.2303,  1.0529],
        [ 0.9580, -0.4162,  1.3788]])


【メモ】

どの操作もメソッド名の後に``_``をつけることで、変数の内容を出力結果で置き換えることができます。

例えば、``y.add_(x)``の場合xとyの値を加算した結果はyに上書きして、格納されます。

NumPyと同様、インデクシングやスライシングを行うことも可能です。

In [ ]:
print(x[:, 1])

tensor([ 0.7701,  1.3643,  0.8513,  0.9941, -0.7676])


リサイズ: tensorの形を変えたい場合は ``torch.view``を使用してください:



In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


``.item()``を使用すると、要素を1つしか持たないtensorから、中身の数値だけを取り出すことができます。


In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7015])
0.7015043497085571


**参考:**

PyTorchでは、転置、インデックシング、スライシング、演算処理、線形代数、乱数生成などの100を超える機能が提供されています。詳しくは[こちら](https://pytorch.org/docs/stable/torch.html)をご覧ください。

NumPyとの接続
------------

PyTorchではTorch TensorからNumPy Arrayへの変換やその逆を簡単に行うことできます。

（Torch TensorがCPU上にある場合）Torch TensorとNumPy Arrayはメモリ上の同じ領域に配置され、変換することができます。

（日本語訳注：そのためメモリ上で新たなコピー操作などは不要であり、変換コストは少なくて、変換効率が良いです。）


Torch Tensorから NumPy Arrayへの変換
--------




In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


メモリを共有しているため、Torch Tensorの値がNumPy Arrayにも反映されることが分かります。



In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


NumPy ArrayからTorch Tensorへの変換
---------

NumPy ArrayからTorch Tensorへの変換も、容易に可能です。



In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensorを除き、CPU上のすべてのtensorはNumPyへの変換、およびその逆（NumpyからTensor）に対応しています。


CUDA Tensors（CUDA テンソル）
------------

tensorは ``.to`` メソッドを使用することであらゆるデバイス上のメモリへと移動させることができます。

In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!


# 日本語訳注：
# tensor([1.8299], device='cuda:0')
# tensor([1.8299], dtype=torch.float64)
# のような出力がセルのあとに表示されれば、GPUでのCUDAでのテンソル計算が成功しています。
# もし、何も表示されなければ、GPU使用モードになっていないので、↓のセルの説明を読んで、GPUを使用可能な状態にしてみてください。

tensor([1.7015], device='cuda:0')
tensor([1.7015], dtype=torch.float64)


日本語訳注：Google ColaboratoryでCUDA、すなわちGPUを使用可能にするには、上部メニューの「ランタイム」を選択し、「ランタイムのタイプを変更」で、「ハードウェア アクセラレータ」にGPUを選択します。

上記で、現在のランタイムの環境を確認し、GPUでなければ、GPUに設定して、上記セルを実行してみてください。

以上。